#
# Use this configuration file to control what RobotPy packages are installed
# on your RoboRIO
#

[tool.robotpy]

# Version of robotpy this project depends on
# to see what versions are available: https://pypi.org/pypi/robotpy/json
robotpy_version = "2024.1.1.3"


# Which extra RobotPy components should be installed
# -> equivalent to `pip install robotpy[extra1, ...]
robotpy_extras = [
    # "all"
    "apriltag",
    # "commands2"
    # "cscore"
    # "navx",
    # "pathplannerlib"
    # "phoenix5"
    # "phoenix6"
    # "playingwithfusion"
    "rev",
    # "romi"
    "sim",
    # "xrp"
]

# Other pip packages to install
requires = [
    "photonlibpy",
    "debugpy==1.6.7",
    "robotpy-commands-v2==2024.0.0b4",
    #"numpy==1.26.3"
    #"numpy==1.25.2",
    "robotpy-navx==2024.1.0"
]
